on:
  push:
    branches:
    - main

jobs:
  sscan:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v6

    - name: PWD
      shell: bash
      run: |
        pwd;
        find . -type f -print0 | xargs -0 sha256sum > /tmp/before.out

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: .
        base: 'main~2'
        head: main
        extra_args: --log-level=2 --results=verified,unknown

    - name: Pretend we did a notification
      shell: bash
      run: |
        find . -type f -print0 | xargs -0 sha256sum > /tmp/after.out
        diff -u /tmp/before.out  /tmp/after.out
        echo "Note that this information has gone nowhere"
