on:
  push:
    branches:
    - main

jobs:
  sscan:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v6

    - name: PWD
      shell: bash
      run: |
        pwd;
        find . -type f -print0 | xargs -0 sha256sum > /tmp/before.out

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ""
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --log-level=2 --results=verified,unknown

    - name: scan-push-4-to-3
      uses: trufflesecurity/trufflehog@main
      with:
        base: ${{ github.ref_name }}~4
        head: ${{ github.ref_name }}~3
        extra_args: --results=verified,unknown

    - name: scan-push-3-to-2
      uses: trufflesecurity/trufflehog@main
      with:
        base: ${{ github.ref_name }}~3
        head: ${{ github.ref_name }}~2
        extra_args: --results=verified,unknown

    - name: scan-push
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --results=verified,unknown

    - name: Pretend we did a notification
      shell: bash
      run: |
        find . -type f -print0 | xargs -0 sha256sum > /tmp/after.out
        diff -u /tmp/before.out  /tmp/after.out
        echo "Note that this information has gone nowhere"
